# Generated by Django 2.2.9 on 2020-01-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_code', models.IntegerField()),
                ('member_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='code',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
