# Generated by Django 2.2.9 on 2020-01-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManagement', '0002_auto_20200116_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password_key',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(verbose_name='Ending Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(verbose_name='Starting date'),
        ),
    ]
